name: hey_notes
description: "A simple Flutter note-taking app with local storage using Hive."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  share_plus: ^7.2.1
  google_fonts: ^6.1.0 # Kept for fallback if needed, but Avenir is primary
  uuid: ^4.2.2
  path: ^1.8.3
  permission_handler: ^11.3.0
  pdf: ^3.10.8
  printing: ^5.11.1
  flutter_native_splash: ^2.4.6
  equatable: ^2.0.7
  animate_do: ^4.2.0
  flutter_quill: ^11.4.2
  get_it: ^8.2.0
  gap: ^3.0.1
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  swift_alert: ^1.0.0
  logger: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  # Add your font files here
  # Using google_fonts package for Avenir
  # No need to declare fonts here when using google_fonts package

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/splash/
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # Fonts configuration
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir Light.ttf
          weight: 300
        - asset: assets/fonts/Avenir Regular.ttf
          weight: 400
        - asset: assets/fonts/Avenir Book.ttf
          weight: 500
        - asset: assets/fonts/Avenir Heavy.ttf
          weight: 700
        - asset: assets/fonts/Avenir Black.ttf
          weight: 900

# Splash screen configuration
flutter_native_splash:
  color: "#FFFFFF"  # Background color of the splash screen
  image: assets/splash/heynotes_logo.png  # Path to your splash screen image
  android: true
  ios: true
  web: false
  android_12:
    image: assets/splash/heynotes_logo.png
    icon_background_color: "#FFFFFF"
